name: example
description: Example for yet another layout builder.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yet_another_layout_builder:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  build_config: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/styles.xml
    - assets/styles2.xml
    - assets/external_data.xml
    - assets/blocks.xml
    - assets/listview.xml
    - assets/interaction.xml
    - assets/semi_const.xml
