name: yet_another_layout_builder
description: Yet another Flutter library for building layouts from xml assets (YALB). Using builder for
  generating most of needed code to perform transform from xml to widgets.
version: 0.1.0
homepage: https://github.com/TheTosters/YetAnotherLayoutBuilder
repository: https://github.com/TheTosters/YetAnotherLayoutBuilder

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^3.0.0
  build: ^2.0.0
  xml: ^5.3.1
  validators: ^3.0.0
  path: ^1.8.0
  processing_tree: ^0.2.1
  collection: ^1.1.15
  logging: ^1.0.2
  glob: ^2.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  #dart_code_metrics: ^4.8.1
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  build_config: ^1.0.0
