name: yet_another_layout_builder
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/TheTosters/YetAnotherLayoutBuilder
repository: https://github.com/TheTosters/YetAnotherLayoutBuilder

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^2.0.0
  build: ^2.0.0
  xml: ^5.3.1
  validators: ^3.0.0
  path: ^1.8.0
  processing_tree: ^0.2.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dart_code_metrics: ^4.1.0
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  build_config: ^1.0.0
